/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.atbm2.coso;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class chuyencoso extends javax.swing.JFrame {
    decimaltohex covert=new decimaltohex();
    /**
     * Creates new form chuyencoso
     */
    public chuyencoso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbb_from = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbb_to = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_input = new javax.swing.JTextArea();
        btn_chuyen = new javax.swing.JButton();
        btn_swap = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_output = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Từ");

        cbb_from.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thập phân", "Nhị phân", "Thập lục phân" }));
        cbb_from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_fromActionPerformed(evt);
            }
        });

        jLabel2.setText("Sang");

        cbb_to.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhị phân", "Thập phân", "Thập lục phân" }));

        jLabel3.setText("Nhập số:");

        txt_input.setColumns(20);
        txt_input.setRows(5);
        jScrollPane1.setViewportView(txt_input);

        btn_chuyen.setText("Chuyển đổi");
        btn_chuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chuyenActionPerformed(evt);
            }
        });

        btn_swap.setText("Hoán đổi hệ cơ số");
        btn_swap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_swapActionPerformed(evt);
            }
        });

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        jLabel4.setText("Kết quả:");

        txt_output.setColumns(20);
        txt_output.setRows(5);
        jScrollPane2.setViewportView(txt_output);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_chuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_swap)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cbb_from, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cbb_to, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(130, 130, 130))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbb_to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbb_from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_chuyen)
                    .addComponent(btn_swap)
                    .addComponent(btn_reset))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean checkbinary(long num){
        if (num == 0 || num == 1
            || num < 0) {
            return false;
        }
       
        while (num != 0) {
            
            if (num % 10 > 1) {
                return false;
            }
            num = num / 10;
        }
        return true;
    }
    private void btn_chuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chuyenActionPerformed
        // TODO add your handling code here:
        String from = cbb_from.getSelectedItem().toString();
        String to = cbb_to.getSelectedItem().toString();
        String input = txt_input.getText();
        String chr = "abcdef";
        if(!input.equals("")){
            if(from.equals("Thập phân")){
                try{
                    if(!input.matches("^\\d*\\.?\\d+$") && (checkbinary(Integer.parseInt(input)) == false)){
                        JOptionPane.showMessageDialog(null, "Đây không phải số thập phân, hãy nhập số thập phân!");
                    }
                    if(to.equals("Nhị phân")){ 
                        binary_convert obj = new binary_convert(input,to);                   
                            txt_output.setText(obj.thap_sang_nhi());                  
                        }
                }
                catch(Exception ex){
                    JOptionPane.showMessageDialog(null, "Đây không phải số thập phân, hãy nhập số thập phân!");
                }
            }
            else if(from.equals("Nhị phân")){
                long inputnum = 0;
                try{
                    inputnum = Long.parseLong(input);
                    if(!checkbinary(inputnum)){
                     JOptionPane.showMessageDialog(null, "Đây không phải số nhị phân, hãy nhập số nhị phân!");
                    }
                    else{
                        if(to.equals("Thập lục phân")){         
                        binary_convert obj = new binary_convert(input,to);
                        if(obj.thaplucphan() == null){
                            JOptionPane.showMessageDialog(null, "Đây không phải số nhị phân, hãy nhập số nhị phân!");
                        }
                        else{
                            txt_output.setText(obj.thaplucphan());
                        }
                        }
                        
                        if(to.equals("Thập phân")){ 
                        binary_convert obj = new binary_convert(input,to);                   
                            txt_output.setText(obj.nhi_sang_thap());                  
                        }
                   }
                }
                catch(Exception ex){
                    JOptionPane.showMessageDialog(null, "Đây không phải số nhị phân, hãy nhập số nhị phân!");
                }
                
            }
            else if(from.equals("Thập lục phân")){
                String inputhoa = input.toUpperCase();
                if(!inputhoa.matches("-?[0-9a-fA-F]+")){
                    JOptionPane.showMessageDialog(null, "Đây không phải số thập lục phân, hãy nhập số thập lục phân!");
                }
                else{
                    hex_convert obj = new hex_convert(inputhoa,to);
                    txt_output.setText(obj.chuyendoi());
                }
            }
            if(from.equals(to)){
                txt_output.setText(input);
            }
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Hãy nhập số để chuyển đổi!");
        }
       if(from.equals("Thập phân")&& to.equals("Thập lục phân") && input.matches("^\\d*\\.?\\d+$")){ 
           int in=Integer.parseInt(input);
           txt_output.setText(covert.decimalcvtohex(in));
       }
        String inputhoa = input.toUpperCase();
       if(from.equals("Thập lục phân")&& to.equals("Thập phân") && inputhoa.matches("-?[0-9a-fA-F]+")){ 
           String out=String.valueOf(covert.hexToDecimal(input));
           txt_output.setText(out);
       }
    }//GEN-LAST:event_btn_chuyenActionPerformed

    private void btn_swapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_swapActionPerformed
        // TODO add your handling code here:
//        Object obj = cbb_to.getSelectedObjects();
//        cbb_from.setSelectedItem(cbb_to.getSelectedObjects());
//        cbb_to.setSelectedItem(obj);
        String from = cbb_from.getSelectedItem().toString();
        String to = cbb_to.getSelectedItem().toString();
        for(int i=0;i< cbb_to.getItemCount();i++){
            if(from.equals(cbb_to.getItemAt(i))){
                cbb_to.setSelectedIndex(i);
                break;
            }
        }
        for(int i=0;i< cbb_from.getItemCount();i++){
            if(to.equals(cbb_from.getItemAt(i))){
                cbb_from.setSelectedIndex(i);
                break;
            }
        }
        txt_input.setText("");
        txt_output.setText("");
    }//GEN-LAST:event_btn_swapActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        txt_input.setText("");
        txt_output.setText("");
    }//GEN-LAST:event_btn_resetActionPerformed

    private void cbb_fromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_fromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbb_fromActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chuyencoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chuyencoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chuyencoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chuyencoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chuyencoso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_chuyen;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_swap;
    private javax.swing.JComboBox<String> cbb_from;
    private javax.swing.JComboBox<String> cbb_to;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txt_input;
    private javax.swing.JTextArea txt_output;
    // End of variables declaration//GEN-END:variables
}
